export { IParser } from './src/main/ets/parse/IParser';

export { Lyric } from './src/main/ets/bean/Lyric'

export { LyricLine } from './src/main/ets/bean/LyricLine'

export { LyricParser } from './src/main/ets/parse/LyricParser'

export { FileParser } from './src/main/ets/parse/FileParser'

export { LyricView } from './src/main/ets/view/LyricView'

export { LyricView2 } from './src/main/ets/view/LyricView2'

export { LyricController } from './src/main/ets/LyricController'

export { LyricHelper } from './src/main/ets/LyricHelper'

// new component
export { Lrc } from './src/main/ets/bean/Lrc'

export { LrcLine } from './src/main/ets/bean/LrcLine'

export { LrcWord } from './src/main/ets/bean/LrcWord'

export { CcLyricView } from './src/main/ets/view/CcLyricView'

export { CcLyricController } from './src/main/ets/CcLyricController'

export { CcLyricController as CcLrcController } from './src/main/ets/CcLyricController'