export { IParser } from './src/main/ets/parse/IParser';

export { Lyric } from './src/main/ets/bean/Lyric'

export { LyricLine } from './src/main/ets/bean/LyricLine'

export { LyricParser } from './src/main/ets/parse/LyricParser'

export { FileParser } from './src/main/ets/parse/FileParser'

export { LyricView } from './src/main/ets/view/LyricView'

export { LyricView2 } from './src/main/ets/view/LyricView2'

export { LyricController } from './src/main/ets/LyricController'

export { LyricHelper } from './src/main/ets/LyricHelper'

export { CcLyricView } from './src/main/ets/view/CcLyricView'
